version: '3'
services:
  db:
    image: mariadb:10.4.13
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./model/init:/docker-entrypoint-initdb.d
      - ./model/data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=' ]

